common/urls.py
from django.conf.urls import url

from . import views

app_name = 'common'

urlpatterns = [
    url(r'^registration/$', views.registration, name='registration'),
    url(r'^authentication_user/$', views.authentication_user, name='authentication_user'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^registration/(?P<code>\w+\-\w+\-\w+)/$', views.complete_email, name='complete_email'),
]

posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^main_page/(?P<page>\d+)/$', views.main_page, name='main_page'),
    url(r'^create_post/$', views.create_post, name='create_post'),
    url(r'^do_like/$', views.do_like, name='do_like'),
    url(r'^post_detail/(?P<post_id>\d+)/(?P<page>\d+)/$', views.post_detail, name='post_detail'),
]

posts_network/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^common/', include('common.urls')),
    url(r'^posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from common.models import CustomUser


class Post(models.Model):
    user = models.ForeignKey(CustomUser)
    title = models.CharField(max_length=32)
    body = models.TextField(max_length=1024, blank=True)
    image = models.ImageField(upload_to='image/post/', blank=True)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post)
    user = models.ForeignKey(CustomUser)
    body = models.TextField(max_length=1024)

    def __str__(self):
        return "Comment {}, post {}".format(self.id, self.post.title)


class Like(models.Model):
    post = models.ForeignKey(Post, related_name='like_post')
    user = models.ForeignKey(CustomUser)

    def __str__(self):
        return "Like {}, post {}".format(self.id, self.post.title)

posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('user', 'title', 'body', 'image',)

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['user'].widget = self.fields['user'].hidden_widget()


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('post', 'user', 'body',)

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['user'].widget = self.fields['user'].hidden_widget()
        self.fields['post'].widget = self.fields['post'].hidden_widget()

posts/views.py
from django.contrib.auth.decorators import login_required
from django.db.models.query import Prefetch
from django.db.models.query_utils import Q
from django.shortcuts import render, redirect
from django.db.models import Count

from .forms import PostForm, CommentForm
from .models import Post, Like, Comment
from common.models import CustomUser


def get_page(page, data):
    """
    Pagination
    """
    page_next = (page + 1) if ((page + 1) <= len(data) / 5) else page
    page_prev = (page - 1) if ((page - 1) >= 0) else page
    return page_next, page_prev


@login_required(login_url='/common/authentication_user/')
def do_like(request):
    back_link = '/posts/main_page/'
    if request.method == 'POST':
        post = request.POST.get('like')
        if post:
            user = request.user
            if Like.objects.filter(post_id=post, user_id=user.id).exists():
                Like.objects.filter(post_id=post, user_id=user.id).delete()
            else:
                Like.objects.create(post_id=post, user_id=user.id)
        link = request.META.get('HTTP_REFERER')
        if link:
            back_link = '/' + link.split('/', 3)[-1]
    return redirect(back_link)


@login_required(login_url='/common/authentication_user/')
def post_detail(request, post_id, page=0):
    user = request.user
    posts = Post.objects.annotate(Count('like_post'))
    post = posts.get(id=post_id)
    comments = Comment.objects.filter(post=post)
    page = int(page)
    page_next, page_prev = get_page(page, comments)
    comments = comments[page * 5:page * 5 + 5]
    if request.method == 'POST':
        form = CommentForm(request.POST)
        form.data._mutable = True
        form.data['user'] = user.id
        form.data['post'] = post.id
        if form.is_valid():
            form.save()
        redirect('posts:main_page', 0)
    else:
        form = CommentForm()
    return render(request, 'posts/post_detail.html', {'post': post, 'comments': comments,
                                                      'form': form, 'page_next': page_next,
                                                      'page_prev': page_prev})


def get_countries_cities(posts):
    """
    Returns the countries and cities of users who made posts
    """
    users_id = list(set(post.user.id for post in posts))
    users = CustomUser.objects.filter(id__in=users_id)
    countries = users.distinct('country')
    cities = users.distinct('city')
    countries = [user.country for user in countries]
    cities = [user.city for user in cities]
    return countries, cities


def get_filter(request, posts):
    """
    Filter: title or body, country, city
    """
    if request.GET.get('text'):
        posts = posts.filter(Q(body__contains=request.GET.get('text')) | Q(title__contains=request.GET.get('text')))
    if request.GET.get('country') or request.GET.get('city'):
        users = CustomUser.objects.all()
        if request.GET.get('country'):
            posts = posts.filter(user__in=users.filter(country=request.GET.get('country')))
        if request.GET.get('city'):
            posts = posts.filter(user__in=users.filter(city=request.GET.get('city')))
    return posts


@login_required(login_url='/common/authentication_user/')
def main_page(request, page=0):
    posts = Post.objects.annotate(Count('like_post')).order_by('-id')
    if request.method == 'GET':
        posts = get_filter(request, posts)
    countries, cities = get_countries_cities(posts)
    page = int(page)
    page_next, page_prev = get_page(page, posts)
    posts = posts[page * 5:page * 5 + 5]
    return render(request, 'posts/main_page.html', {'posts': posts, 'page_next': page_next,
                                                    'page_prev': page_prev, 'countries': countries,
                                                    'cities': cities})


@login_required(login_url='/common/authentication_user/')
def create_post(request):
    user = request.user
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        form.data._mutable = True
        form.data['user'] = user.id
        if form.is_valid():
            form.save()
        return redirect('posts:main_page', 0)
    else:
        form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})

posts/templates/posts/create_post.html
{% extends 'posts/main.html' %}
{% block title %}Create Post{% endblock %}

{% block body %}
<form method="POST" class="post-form form-horizontal" role="form" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="save btn btn-default" value="Save">
</form>
{% endblock %}

posts/templates/posts/home_page.html
{% extends 'posts/main.html' %}
{% block title %}Home Page{% endblock %}

{% block body %}
<div class="row">

        <div class="col-sm-8 blog-main">

          {% for advert in adverts %}
              <div class="blog-post">

              </div><!-- /.blog-post -->
          {% endfor %}

          <ul class="pager">
            <li><a href="#?{{ request.GET.urlencode }}">Назад</a></li>
            <li><a href="#?{{ request.GET.urlencode }}">Далее</a></li>
          </ul>

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">

        </div><!-- /.blog-sidebar -->
</div><!-- /.row -->
{% endblock %}

posts/templates/posts/main.html
{% load staticfiles %}
<!DOCTYPE html>
<!-- saved from url=(0038)http://bootstrap-3.ru/examples/cover/# -->
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {%block pre_head%}{%endblock%}
    <link rel="stylesheet" href="{% static 'posts/css/bootstrap.css' %}">
    <link href="{% static 'posts/css/blog.css' %}" rel="stylesheet">
    <script type="text/javascript" src="{% static 'posts/js/jquery.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'posts/js/bootstrap.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'posts/js/docs.min.js' %}" ></script>
</head>

  <body><div class="blog-masthead">
      <div class="container">
        <nav class="sort blog-nav">
          <a class="blog-nav-item" href="{% url 'posts:main_page' 0 %}">Main Page</a>
          <a class="blog-nav-item" href="{% url 'posts:create_post' %}">Create Post</a>
            <div class="navbar-right blog-nav-item">{{ user.email }}</div>
            <div class="navbar-right blog-nav-item"><a href="{% url 'common:logout_view' %}">Log-Out</a></div>
        </nav>
      </div>
    </div>

    <div class="container">
        <div class="blog-header">

      </div>
        {% block body %}{% endblock %}


    </div><!-- /.container -->

    <div class="blog-footer">
      <p>Разработал boyko.nikita@gmail.com</p>
        <p>Благодарность <a href="http://bootstrap-3.ru">http://bootstrap-3.ru</a></p>
      <p>Blog template built for <a href="http://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    </div>

<script>
    $(document).ready(function () {
        $('.sort a').each(function () { //определяем общий класс меню
            var location = window.location.href.split('?')[0];
            var link = this.href;
            if (location == link) {
                $(this).addClass('active'); //добавляем класс активной вкладке
            }
        });
    });
</script>
</body>
</html>

posts/templates/posts/main_page.html
{% extends 'posts/main.html' %}
{% block title %}Main Page{% endblock %}

{% block body %}
<div class="row">

        <div class="col-sm-8 blog-main">

            {% for post in posts %}
              <div class="blog-post">
                <a href="{% url 'posts:post_detail' post.id 0 %}"><h2 class="blog-post-title">{{ post.title }}</h2></a>
                  <p class="blog-post-meta">{{ post.user.first_name }} {{ post.user.last_name }}<br>
                  {{ post.create_at }} {{ post.user.email }}<br>
                  {{ post.user.country }} {{ post.user.city }}</p>
                  <p>{{ post.body }}</p>
                  {% if post.image %}
                    <p><img src="{{ post.image.url }}"></p>
                  {% endif %}
                <form method="POST" action="{% url 'posts:do_like' %}">{% csrf_token %}
                    <input type="hidden" name="like" value="{{ post.id }}">
                    <p class="like" class="blog-post-meta"><input type="submit" value="like">
                    {{ post.like_post__count }}</p>
                </form>
              </div><!-- /.blog-post -->
            {% endfor %}


          <ul class="pager">
            <li><a href="{% url 'posts:main_page' page_prev %}?{{ request.GET.urlencode }}">Previous</a></li>
            <li><a href="{% url 'posts:main_page' page_next %}?{{ request.GET.urlencode }}">Next</a></li>
          </ul>

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <form method="GET" action="{% url 'posts:main_page' 0 %}">
                <input type="hidden" name="route" value="{{ request.GET.urlencode }}">
                <p><input type="text" size="30" name="text"></p> <p><input type="submit" value="Search"></p>
            </form>
            <hr>
            <div class="btn-group status-filter">
              <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">Country filter<span class="caret"></span></button>
                <ul class="dropdown-menu" role="menu">
                    {% for country in countries %}
                        <li><a href="{% url 'posts:main_page' 0 %}?{{ request.GET.urlencode }}&country={{ country }}">{{ country }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <hr>
            <div class="btn-group status-filter">
              <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">City filter<span class="caret"></span></button>
                <ul class="dropdown-menu" role="menu">
                    {% for city in cities %}
                        <li><a href="{% url 'posts:main_page' 0 %}?{{ request.GET.urlencode }}&city={{ city }}">{{ city }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div><!-- /.blog-sidebar -->
</div><!-- /.row -->
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'posts/main.html' %}
{% block title %}Main Page{% endblock %}

{% block body %}
<div class="row">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
            <h2 class="blog-post-title">{{ post.title }}</h2>
            <p class="blog-post-meta">{{ post.create_at }} {{ post.user.email }}</p>
              <p>{{ post.body }}</p>
              {% if post.image %}
                <p><img src="{{ post.image.url }}"></p>
              {% endif %}
            <form method="POST" action="{% url 'posts:do_like' %}">{% csrf_token %}
                <input type="hidden" name="like" value="{{ post.id }}">
                <p class="like" class="blog-post-meta"><input type="submit" value="like">
                {{ post.like_post__count }}</p>
            </form>
          </div><!-- /.blog-post -->
            <form method="POST">{% csrf_token %}
            {{ form.as_p }}
                <input type="submit" value="Save comment">
            </form>
            <hr>
            <div class="row">
                {% for comment in comments %}
                {{ comment.user.email }}
              <div class="alert alert-success">{{comment.body }}</div>
                {% endfor %}
            </div>

          <ul class="pager">
            <li><a href="{% url 'posts:post_detail' post.id page_prev %}?{{ request.GET.urlencode }}">Previous</a></li>
            <li><a href="{% url 'posts:post_detail' post.id page_next %}?{{ request.GET.urlencode }}">Next</a></li>
          </ul>

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">

        </div><!-- /.blog-sidebar -->
</div><!-- /.row -->
{% endblock %}